name: Scheduled Commit

on:
  schedule:
    - cron: '0 */4 * * *' 

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: 'checkout codes'
      uses: actions/checkout@v2

    - name: 'config git'
      run: |
        git config --global user.name "a992681784"
        git config --global user.email "a992681784@163.com"

    - name: 'record'
      run: |
        echo "Record for $(date)" >> record.txt
        git add record.txt
        git commit -m "Scheduled commit record for $(date)"
        git push
